# Generated by Django 2.0 on 2018-07-02 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnioPrecio',
            fields=[
                ('anio', models.IntegerField(db_column='ANIOPRECIO', primary_key=True, serialize=False)),
            ],
            options={
                'managed': True,
                'db_table': 'ANIOPRECIO',
            },
        ),
        migrations.CreateModel(
            name='CostoEconomico',
            fields=[
                ('idprocesoeconomico', models.AutoField(db_column='IDPROCESOECONOMICO', primary_key=True, serialize=False)),
                ('ingresos', models.DecimalField(db_column='INGRESOS', decimal_places=20, max_digits=50)),
                ('costotratamiento', models.DecimalField(db_column='COSTOTRATAMIENTO', decimal_places=20, max_digits=50)),
                ('costodesmontajemanual', models.DecimalField(db_column='COSTODESMONTAJEMANUAL', decimal_places=20, max_digits=50)),
                ('costotrituracion', models.DecimalField(db_column='COSTOTRITURACION', decimal_places=20, max_digits=50)),
                ('costoposttratamiento', models.DecimalField(db_column='COSTOPOSTTRATAMIENTO', decimal_places=20, max_digits=50)),
            ],
            options={
                'managed': True,
                'db_table': 'COSTOECONOMICO',
            },
        ),
        migrations.CreateModel(
            name='Densidad',
            fields=[
                ('iddensidad', models.AutoField(db_column='IDDENSIDAD', primary_key=True, serialize=False)),
                ('densidad', models.DecimalField(db_column='DENSIDAD', decimal_places=20, max_digits=50)),
            ],
            options={
                'managed': True,
                'db_table': 'DENSIDAD',
            },
        ),
        migrations.CreateModel(
            name='DensidadMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(db_column='VALOR', decimal_places=20, max_digits=50)),
                ('iddensidad', models.ForeignKey(db_column='IDDENSIDAD', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Densidad')),
            ],
            options={
                'db_table': 'DENSIDADMATERIAL',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idequipo', models.AutoField(db_column='IDEQUIPO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=45)),
            ],
            options={
                'managed': True,
                'db_table': 'EQUIPO',
            },
        ),
        migrations.CreateModel(
            name='EquipoEntrada',
            fields=[
                ('idequipoentrada', models.AutoField(db_column='IDEQUIPOENTRADA', primary_key=True, serialize=False)),
                ('anio', models.IntegerField(db_column='ANIO')),
                ('idequipo', models.ForeignKey(db_column='IDEQUIPO', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Equipo')),
            ],
            options={
                'managed': True,
                'db_table': 'EQUIPOENTRADA',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idgrupo', models.AutoField(db_column='IDGRUPO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=45)),
            ],
            options={
                'managed': True,
                'db_table': 'GRUPO',
            },
        ),
        migrations.CreateModel(
            name='ImpuezaMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(db_column='VALOR', decimal_places=20, max_digits=50)),
            ],
            options={
                'managed': True,
                'db_table': 'IMPUREZAMATERIAL',
            },
        ),
        migrations.CreateModel(
            name='Impureza',
            fields=[
                ('idimpureza', models.AutoField(db_column='IDIMPUREZA', primary_key=True, serialize=False)),
                ('etapa', models.IntegerField(db_column='ETAPA')),
                ('parametro', models.DecimalField(db_column='PARAMETRO', decimal_places=20, max_digits=50)),
            ],
            options={
                'managed': True,
                'db_table': 'IMPUREZA',
            },
        ),
        migrations.CreateModel(
            name='MasaEntrada',
            fields=[
                ('idmasaentrada', models.AutoField(db_column='IDMASAENTRADA', primary_key=True, serialize=False)),
                ('masa', models.DecimalField(db_column='MASA', decimal_places=20, max_digits=50)),
                ('idequipoentrada', models.ForeignKey(db_column='IDEQUIPOENTRADA', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.EquipoEntrada')),
            ],
            options={
                'managed': True,
                'db_table': 'MASAENTRADA',
            },
        ),
        migrations.CreateModel(
            name='Masasalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valormasa', models.DecimalField(db_column='VALORMASA', decimal_places=20, max_digits=50)),
            ],
            options={
                'managed': True,
                'db_table': 'MASASALIDA',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idmaterial', models.AutoField(db_column='IDMATERIAL', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=45)),
            ],
            options={
                'managed': True,
                'db_table': 'MATERIAL',
            },
        ),
        migrations.CreateModel(
            name='MaterialPrecio',
            fields=[
                ('idmaterialprecio', models.AutoField(db_column='IDMATERIALPRECIO', primary_key=True, serialize=False)),
                ('precioreventa', models.DecimalField(db_column='PRECIOREVENTA', decimal_places=20, max_digits=50)),
                ('anio', models.ForeignKey(db_column='ANIOPRECIO', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.AnioPrecio')),
                ('idmaterial', models.ForeignKey(db_column='IDMATERIAL', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Material')),
            ],
            options={
                'managed': True,
                'db_table': 'MATERIALPRECIO',
            },
        ),
        migrations.CreateModel(
            name='Parametroseconomicos',
            fields=[
                ('idparametroseconomicos', models.AutoField(db_column='IDPARAMETROSECONOMICOS', primary_key=True, serialize=False)),
                ('incineracion', models.DecimalField(db_column='INCINERACION', decimal_places=20, max_digits=50)),
                ('desmontajemanual', models.DecimalField(db_column='DESMONTAJEMANUAL', decimal_places=20, max_digits=50)),
                ('posttratamiento', models.DecimalField(db_column='POSTTRATAMIENTO', decimal_places=20, max_digits=50)),
                ('trituracion40', models.DecimalField(db_column='TRITURACION40', decimal_places=20, max_digits=50)),
                ('trituracion15', models.DecimalField(db_column='TRITURACION15', decimal_places=20, max_digits=50)),
                ('pasospureza', models.IntegerField(db_column='PASOSPUREZA')),
                ('patametroreventa1', models.DecimalField(db_column='PATAMETROREVENTA1', decimal_places=20, max_digits=50)),
                ('patametroreventa2', models.DecimalField(db_column='PATAMETROREVENTA2', decimal_places=20, max_digits=50)),
                ('patametroreventa3', models.DecimalField(db_column='PATAMETROREVENTA3', decimal_places=20, max_digits=50)),
                ('marr', models.DecimalField(db_column='MARR', decimal_places=20, max_digits=50)),
            ],
            options={
                'managed': True,
                'db_table': 'PARAMETROSECONOMICOS',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('idproceso', models.AutoField(db_column='IDPROCESO', primary_key=True, serialize=False)),
                ('proceso', models.CharField(db_column='PROCESO', max_length=45)),
                ('costotratamiento', models.DecimalField(db_column='COSTOTRATAMIENTO', decimal_places=20, max_digits=50)),
                ('costoinversion', models.DecimalField(db_column='COSTOINVERSION', decimal_places=20, max_digits=50)),
                ('rendimientominimo', models.DecimalField(blank=True, db_column='RENDIMIENTOMINIMO', decimal_places=20, max_digits=50, null=True)),
                ('incrementorendimiento', models.DecimalField(blank=True, db_column='INCREMENTORENDIMIENTO', decimal_places=20, max_digits=50, null=True)),
                ('tiempodepreciacion', models.DecimalField(blank=True, db_column='TIEMPODEPRECIACION', decimal_places=20, max_digits=50, null=True)),
                ('loop', models.CharField(db_column='LOOP', max_length=45)),
                ('procesoid', models.IntegerField(db_column='PROCESOID', null=True)),
                ('mantenimientotonelada', models.DecimalField(blank=True, db_column='MANTENIMIENTOTONELADA', decimal_places=20, max_digits=50, null=True)),
                ('manoobratonelada', models.DecimalField(blank=True, db_column='MANOOBRATONELADA', decimal_places=20, max_digits=50, null=True)),
                ('energia', models.DecimalField(blank=True, db_column='ENERGIA', decimal_places=20, max_digits=50, null=True)),
                ('otros', models.DecimalField(blank=True, db_column='OTROS', decimal_places=20, max_digits=50, null=True)),
                ('iddensidad', models.ForeignKey(blank=True, db_column='IDDENSIDAD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Densidad')),
                ('idgrupo', models.ForeignKey(db_column='GRUPO', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Grupo')),
            ],
            options={
                'managed': True,
                'db_table': 'PROCESO',
            },
        ),
        migrations.CreateModel(
            name='ProcesoCalculado',
            fields=[
                ('idprocesocalculado', models.AutoField(db_column='IDPROCESOSCALCULADO', primary_key=True, serialize=False)),
                ('idanioprecio', models.ForeignKey(db_column='ANIOPRECIO', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.AnioPrecio')),
                ('idequipo', models.ForeignKey(db_column='IDEQUIPO', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Equipo')),
                ('idequipoentradafinal', models.ForeignKey(db_column='IDENTRADAFINAL', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ANIOFINAL', to='processes.EquipoEntrada')),
                ('idequipoentradainicio', models.ForeignKey(db_column='IDENTRADAINICIO', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ANIOINICIO', to='processes.EquipoEntrada')),
                ('idprocesos', models.ManyToManyField(to='processes.Proceso')),
            ],
            options={
                'managed': True,
                'db_table': 'PROCESOCALCULADO',
            },
        ),
        migrations.CreateModel(
            name='ProcesoCombinacion',
            fields=[
                ('idprocesocombinacion', models.AutoField(db_column='IDPROCESOCOMBINACION', primary_key=True, serialize=False)),
                ('secuencia', models.IntegerField(db_column='SECUENCIA')),
                ('idmaterial', models.IntegerField(blank=True, db_column='IDMATERIAL', null=True)),
                ('salida', models.IntegerField(db_column='SALIDA')),
                ('idprocesoprevio', models.ForeignKey(db_column='IDPROCESOPREVIO', on_delete=django.db.models.deletion.DO_NOTHING, related_name='idprocesoPre', to='processes.Proceso')),
                ('idprocesosalida', models.ForeignKey(db_column='IDPROCESOSALIDA', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Proceso')),
            ],
            options={
                'managed': True,
                'db_table': 'PROCESOCOMBINACION',
            },
        ),
        migrations.CreateModel(
            name='ProcesoSeparacion',
            fields=[
                ('idprocesosseparacion', models.AutoField(db_column='IDPROCESOSSEPARACION', primary_key=True, serialize=False)),
                ('secuenciaprocesoseparacion', models.IntegerField(db_column='SECUENCIAPROCESOSEPARACION')),
                ('inversion', models.DecimalField(db_column='INVERSION', decimal_places=20, max_digits=50)),
                ('valorneto', models.DecimalField(db_column='VALORNETO', decimal_places=20, max_digits=50)),
            ],
            options={
                'managed': True,
                'db_table': 'PROCESOSEPARACION',
            },
        ),
        migrations.CreateModel(
            name='ProcesoSeparacionId',
            fields=[
                ('idprocesosseparacionid', models.AutoField(db_column='IDPROCESOSSEPARACIONID', primary_key=True, serialize=False)),
                ('anio', models.IntegerField(db_column='ANIO')),
                ('idprocesocalculado', models.ForeignKey(db_column='IDPROCESOCALCULADO', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.ProcesoCalculado')),
            ],
            options={
                'managed': True,
                'db_table': 'PROCESOSEPARACIONID',
            },
        ),
        migrations.CreateModel(
            name='RendimientoProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(db_column='VALOR', decimal_places=20, max_digits=50)),
                ('idmaterial', models.ForeignKey(db_column='IDMATERIAL', on_delete=django.db.models.deletion.DO_NOTHING, related_name='materialidmaterial', to='processes.Material')),
                ('idmaterialreferencia', models.ForeignKey(db_column='IDMATERIALREFERENCIA', on_delete=django.db.models.deletion.DO_NOTHING, related_name='idmaterialRefe', to='processes.Material')),
                ('idproceso', models.ForeignKey(db_column='IDPROCESO', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Proceso')),
            ],
            options={
                'managed': True,
                'db_table': 'RENDIMIENTOPROCESO',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idtipo', models.AutoField(db_column='IDTIPO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=45)),
            ],
            options={
                'managed': True,
                'db_table': 'TIPO',
            },
        ),
        migrations.CreateModel(
            name='TipoImpureza',
            fields=[
                ('idtipoimpureza', models.AutoField(db_column='IDTIPOIMPUREZA', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=45)),
            ],
            options={
                'managed': True,
                'db_table': 'TIPOIMPUREZA',
            },
        ),
        migrations.AddField(
            model_name='procesoseparacion',
            name='idprocesosseparacionid',
            field=models.ForeignKey(db_column='IDPROCESOSSEPARACIONID', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.ProcesoSeparacionId'),
        ),
        migrations.AddField(
            model_name='procesocombinacion',
            name='idprocesosseparacion',
            field=models.ForeignKey(db_column='IDPROCESOSSEPARACION', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PSidprocesosseparacion', to='processes.ProcesoSeparacion'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='idtipo',
            field=models.ForeignKey(db_column='TIPO', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Tipo'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='materiales',
            field=models.ManyToManyField(to='processes.Material'),
        ),
        migrations.AddField(
            model_name='parametroseconomicos',
            name='idproceso',
            field=models.ForeignKey(db_column='IDPROCESO', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Proceso'),
        ),
        migrations.AddField(
            model_name='masasalida',
            name='idmaterial',
            field=models.ForeignKey(db_column='IDMATERIAL', on_delete=django.db.models.deletion.DO_NOTHING, related_name='IDMATERIAL', to='processes.Material'),
        ),
        migrations.AddField(
            model_name='masasalida',
            name='idprocesocombinacion',
            field=models.ForeignKey(db_column='IDPROCESOSCOMBINACION', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.ProcesoCombinacion'),
        ),
        migrations.AddField(
            model_name='masaentrada',
            name='idmaterial',
            field=models.ForeignKey(db_column='IDMATERIAL', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Material'),
        ),
        migrations.AddField(
            model_name='impureza',
            name='idtipoimpureza',
            field=models.ForeignKey(db_column='IDTIPOIMPUREZA', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.TipoImpureza'),
        ),
        migrations.AddField(
            model_name='impuezamaterial',
            name='idimaterial',
            field=models.ForeignKey(db_column='IDMATERIAL', on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdmaterialPri', to='processes.Material'),
        ),
        migrations.AddField(
            model_name='impuezamaterial',
            name='idimaterialreferencia',
            field=models.ForeignKey(db_column='IDMATERIALREFERENCIA', on_delete=django.db.models.deletion.DO_NOTHING, related_name='IdmaterialRef', to='processes.Material'),
        ),
        migrations.AddField(
            model_name='impuezamaterial',
            name='idimpuereza',
            field=models.ForeignKey(db_column='IDIMPUEREZA', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Impureza'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='materiales',
            field=models.ManyToManyField(to='processes.Material'),
        ),
        migrations.AddField(
            model_name='densidadmaterial',
            name='idmaterial',
            field=models.ForeignKey(db_column='MATERIAL_IDMATERIAL', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Material'),
        ),
        migrations.AlterUniqueTogether(
            name='densidad',
            unique_together={('iddensidad', 'densidad')},
        ),
        migrations.AddField(
            model_name='costoeconomico',
            name='idimpureza',
            field=models.ForeignKey(db_column='IDIMPUREZA', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Impureza'),
        ),
        migrations.AddField(
            model_name='costoeconomico',
            name='idparametroseconomicos',
            field=models.ForeignKey(db_column='IDPARAMETROSECONOMICOS', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Parametroseconomicos'),
        ),
        migrations.AddField(
            model_name='costoeconomico',
            name='idprocesocombinacion',
            field=models.ForeignKey(db_column='IDPROCESOSCOMBINACION', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.ProcesoCombinacion'),
        ),
        migrations.AlterUniqueTogether(
            name='rendimientoproceso',
            unique_together={('idmaterial', 'idmaterialreferencia', 'idproceso')},
        ),
        migrations.AlterUniqueTogether(
            name='procesoseparacionid',
            unique_together={('idprocesosseparacionid', 'anio')},
        ),
        migrations.AlterUniqueTogether(
            name='procesoseparacion',
            unique_together={('idprocesosseparacionid', 'secuenciaprocesoseparacion')},
        ),
        migrations.AlterUniqueTogether(
            name='procesocombinacion',
            unique_together={('idprocesosseparacion', 'secuencia')},
        ),
        migrations.AlterUniqueTogether(
            name='proceso',
            unique_together={('idproceso', 'idgrupo', 'idtipo')},
        ),
        migrations.AlterUniqueTogether(
            name='materialprecio',
            unique_together={('anio', 'idmaterial')},
        ),
        migrations.AlterUniqueTogether(
            name='masasalida',
            unique_together={('idprocesocombinacion', 'idmaterial')},
        ),
        migrations.AlterUniqueTogether(
            name='masaentrada',
            unique_together={('idequipoentrada', 'idmaterial')},
        ),
        migrations.AlterUniqueTogether(
            name='impureza',
            unique_together={('idtipoimpureza', 'etapa')},
        ),
        migrations.AlterUniqueTogether(
            name='equipoentrada',
            unique_together={('idequipo', 'anio')},
        ),
        migrations.AlterUniqueTogether(
            name='densidadmaterial',
            unique_together={('iddensidad', 'idmaterial')},
        ),
        migrations.AlterUniqueTogether(
            name='costoeconomico',
            unique_together={('idprocesocombinacion', 'idimpureza')},
        ),
    ]
