# Generated by Django 2.0 on 2018-11-01 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesocombinacion',
            name='idprocesoprevio',
            field=models.ForeignKey(db_column='IDPROCESOPREVIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='idprocesoPre', to='processes.Proceso'),
        ),
        migrations.AlterField(
            model_name='procesocombinacion',
            name='idprocesosalida',
            field=models.ForeignKey(db_column='IDPROCESOSALIDA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Proceso'),
        ),
        migrations.AlterField(
            model_name='procesocombinacion',
            name='salida',
            field=models.IntegerField(db_column='SALIDA', null=True),
        ),
    ]
