# Generated by Django 2.0 on 2018-12-01 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_auto_20181101_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialprecio',
            name='anio',
            field=models.ForeignKey(db_column='ANIOPRECIO', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.AnioPrecio', verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='materialprecio',
            name='idmaterial',
            field=models.ForeignKey(db_column='IDMATERIAL', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='materialprecio',
            name='idmaterialprecio',
            field=models.AutoField(db_column='IDMATERIALPRECIO', primary_key=True, serialize=False, verbose_name='Cod'),
        ),
        migrations.AlterField(
            model_name='materialprecio',
            name='precioreventa',
            field=models.DecimalField(db_column='PRECIOREVENTA', decimal_places=2, max_digits=50, verbose_name='Precio Venta €'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='costoinversion',
            field=models.DecimalField(db_column='COSTOINVERSION', decimal_places=20, max_digits=50, verbose_name='Costo Inversion'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='costotratamiento',
            field=models.DecimalField(db_column='COSTOTRATAMIENTO', decimal_places=20, max_digits=50, verbose_name='Costotra Tamiento'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='energia',
            field=models.DecimalField(blank=True, db_column='ENERGIA', decimal_places=20, max_digits=50, null=True, verbose_name='Energia'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='iddensidad',
            field=models.ForeignKey(blank=True, db_column='IDDENSIDAD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Densidad', verbose_name='Densidad'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='idgrupo',
            field=models.ForeignKey(db_column='GRUPO', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Grupo', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='idtipo',
            field=models.ForeignKey(db_column='TIPO', on_delete=django.db.models.deletion.DO_NOTHING, to='processes.Tipo', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='incrementorendimiento',
            field=models.DecimalField(blank=True, db_column='INCREMENTORENDIMIENTO', decimal_places=20, max_digits=50, null=True, verbose_name='Incremento Rendimiento'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='loop',
            field=models.CharField(db_column='LOOP', max_length=45, verbose_name='Loop'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='manoobratonelada',
            field=models.DecimalField(blank=True, db_column='MANOOBRATONELADA', decimal_places=20, max_digits=50, null=True, verbose_name='Mano Obra Tonelada $'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='mantenimientotonelada',
            field=models.DecimalField(blank=True, db_column='MANTENIMIENTOTONELADA', decimal_places=20, max_digits=50, null=True, verbose_name='Mantenimiento Tonelada $'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='otros',
            field=models.DecimalField(blank=True, db_column='OTROS', decimal_places=20, max_digits=50, null=True, verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='proceso',
            field=models.CharField(db_column='PROCESO', max_length=45, verbose_name='Nombre Proceso'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='procesoid',
            field=models.IntegerField(db_column='PROCESOID', null=True, verbose_name='Proceso Id'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='rendimientominimo',
            field=models.DecimalField(blank=True, db_column='RENDIMIENTOMINIMO', decimal_places=20, max_digits=50, null=True, verbose_name='Rendimiento Minimo'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tiempodepreciacion',
            field=models.DecimalField(blank=True, db_column='TIEMPODEPRECIACION', decimal_places=20, max_digits=50, null=True, verbose_name='Tiempo Depreciacion'),
        ),
    ]
