# Generated by Django 2.0 on 2018-12-01 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_auto_20181201_0221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together={('nombre',)},
        ),
    ]
